### ISSUE TITLE
Ember+ Node is not a Type of String

### ISSUE THREAD

**Issue by MatzeP** [bitfocus/companion-module-generic-emberplus#21] opened 2023-11-17 14:36 UTC
Hi,
I have add a device and want to switch via ember+, but in the logs he wrote that the "Node 4096.1.38.4098.81921.2049 is not of type STRING"
If I use EmberViewer I can switch the value.
![Ember+_Juenger](https://github.com/bitfocus/companion-module-generic-emberplus/assets/25775637/c8f51488-e23c-41c7-827b-bd26ac5e6932)
![Ember+_Juenger_Companion](https://github.com/bitfocus/companion-module-generic-emberplus/assets/25775637/14fac565-d636-4e06-b4cd-d09b9fcaf5fb)
![Ember+_Juenger_connection](https://github.com/bitfocus/companion-module-generic-emberplus/assets/25775637/d4ec897f-d36f-4f1b-981a-ec5290cab0c7)

Can anybody tell me what I make wrong??

Thanks

**Comment by mint-dewit** [comment] 2024-05-04 07:03
Closing as duplicate of #23

**Closed by mint-dewit** 2024-05-04 07:03 UTC
